### ISSUE TITLE
Fields currently in use

### ISSUE THREAD

**Issue by awolfe76** [Conexon/Conexon.github.io#143]
## Fields from `<coop>_sub.geojson`

- subname
- cn_substat
- sub_geoid_any
- all the metric data
  - meters
  - meters_rdof
  - meters_cable
  - meters_fiber
  - meters_telco
  - sub_amt_any
  - sub_amt_50
  - sub_bg_cnt_any
  - sub_bg_cnt_50
  - sub_bg_locs_any

## Fields from `rdof_bg_pnt_<state>.geojson`

- fcc_amt
- geoid

**Comment by feomike** [comment]
closing ....
