### ISSUE TITLE
RDOF Map template edit

### ISSUE THREAD

**Issue by feomike** [Conexon/Conexon.github.io#19]
change BG outline to something more distinctive

@awolfe76 - didn't have time to do this myself this weekend.  can chat Monday about it

**Comment by awolfe76** [comment]
I did mess around with something. Let me check again and I'll post a screen shot here.

**Comment by feomike** [comment]
👍

**Comment by awolfe76** [comment]
I'll go ahead and close this one since #20 took care of it.
