### ISSUE TITLE
RDOF Map Production - Workflow

### ISSUE THREAD

**Issue by feomike** [Conexon/Conexon.github.io#22]
Workflow Overview

1. get info from source table

2. copy the template file to new name

3. edit the newly named file

4. test / final edit

5. intro to Git workflow

**Comment by feomike** [comment]
Background
- we will need 1 RDOF map per request client. 
- MapBox holds tiles sets for
    - each state's Block Group data for RDOF eligible Block Groups.  These tile test are named as rdof_bg_[state] where state is the two letter lower case abbreviation for that state. These tilesets has attributes for:
        - each coop's (that we have assembled meters for) number of meters per eligible meters.  the field name here is a function of the corresponding RUS Number for that coop + `_m`
        - each coop's percent of meters against locations.  the field name here is a function of the corresponding RUS Number for that coop + `_pct`
        - number of locations eligible in that BG.  the field name is `fcc_904`
        - amount of funding in that BG (reserve price). the field name is `fcc_amt`
    - each state's Block data for RDOT eligible Blocks.  These tile test are named as rdof_block_[state] where state is the two letter lower case abbreviation for that state. These tilesets has attributes for:
        - each coop's (that we have assembled meters for) number of meters per eligible meters.  the field name here is a function of the corresponding RUS Number for that coop + `_m`
    - each state's meter data.  these tile sets are named as rdof_meters_[state] where state is the two letter lower case abbreviation for that state.  these tile sets has attributes for:
        - a code for the coop name in the field name `coop_code`

- we will create 1 new html document per requested coop.  
- when we do this, we follow the above workflow.

**Comment by feomike** [comment]
1. Get Info from the source table

for the given coop, us PG admin to get the associated coop_code, rus_no and state from a table in PG.

Steps
-------
1. Using PG Admin connect to this DB `coop_strategy`.
2. Using PG Admin use/modify this statement to help refine and get the coop_code and the rus_no
```
select rus_st, rus_no, rus_nm, conexon_code
	from data.coops 
	where conexon_code is not null
	and rus_st = 'MS'
	order by rus_st;
```
the relevant info you will need for editing is:
    - the `rus_st`
    - the `rus_no`
    - the `conexon_code`

**Comment by feomike** [comment]
2. copy the template file to new name

Steps
------
1. copy the template file to a new file name.  the file name should be all lower case and follow this pattern;
    - rdof_[conexon_code].html

**Comment by feomike** [comment]
3. edit the newly named file

Steps
------

1. edit 
    - line 94 - eg ```rusFld = 'ms028_m';```
        - change the ms028_m to the corresponding value of this coop's rus_no from step 1.  
    - line 95 - eg ```rusFld2 = 'ms028_pct';```
        - change the ms028_pct to the corresponding value of this coop's rus_no from step 1.
    - line 97 - eg ```coopCode = 'COAST';```
        - change the value of `COAST` to the corresponding value of this coop's `conexon_code` from step 1.
    - change lines 109-116 to make reference to the appropriate state codes in the tilesets

**Comment by feomike** [comment]
4. test / final edit

Steps
------

1. after map is published (using either local `python -m SimpleHTTPServer 8000` or wait until a commit is made), edit the zoom scale and centroid values
    - line 89 - enter an appropriate zoom scale for this frame of the map - default is likely 9/10
    - line 90 - enter a center value [x,y]

**Comment by feomike** [comment]
the git workflow
----------------

setting this up, b/c using python locally, you can turn on a web server, and test your html document, before you push it.  once pushed to GitHub, it will generate the web server (about 5 minutes after the pull request is accepted).

using the terminal window (locally).
1. clone the repo
2. in the repo checkout a new branch `git checkout -b <branch_name>`
3. copy the template.html doc to a new doc
4. edit the new doc
5. from the terminal window in the directory where the html document is type $`python -m SimpleHTTPServer 8000`
6. from a browser type `localhost:8000/<document_name>.html`
7. edit the doc, save, hit refresh in the browser until satisfied
8. from the terminal window
    - `git add *`
    - git commit -m 'adding <file_name>
    - git push --set-upstream origin <branch_name>

9. from git, initiate a pull request, and merge it
10. site is live

**Comment by awolfe76** [comment]
See, the README at https://github.com/Conexon/Conexon.github.io/tree/master/coop/rdof, for the UI way of handling this.

**Comment by feomike** [comment]
closing ...
