### ISSUE TITLE
RDOF Map 2 - download issue

### ISSUE THREAD

**Issue by feomike** [Conexon/Conexon.github.io#225]
the data download for Map 2 needs a tweak;
- the GeoID fld is a 12 character number (oxymoron).  its a character field, but is numeric.  there are leading `0`s that need preserved.  the example to test on is any coop in the state of AR.  these have a state FIPS code of `05` so all `geoid` numbers begin `05..`.  right now the download shows only `5..`

**Comment by awolfe76** [comment]
Do we have a client in AR that's live now? I don't see any in the [clients.json file](https://github.com/Conexon/Conexon.github.io/blob/f5731e865e2cef2902dd90e88e78c2496b7eb5ab/coop/data/clients/clients.json). 

I found a coop, ACEC, in AR but I don't have the `acec_sub.geojson` file to use for them. Want to push it when you get a chance @feomike? If a different one if that's easier.

_Sorry if I'm missing an AR client._

**Comment by feomike** [comment]
pr #228 just made the AR clients available.

**Comment by awolfe76** [comment]
This turned out to be the "Numbers" app was removing the leading `0`. The content of the CSV does have it.
