### ISSUE TITLE
Switch to block group (vs substation)

### ISSUE THREAD

**Issue by awolfe76** [Conexon/Conexon.github.io#226]
This change has always been in the background of building out these maps, that at some point we'd need to have the block groups be the trigger for a click event instead of the substations. That time has come.

## Problem 

A quick run down of how this works now ...

1. When the page is loaded it requires a `coopCode` parameter, e.g. `https://conexon.github.io/coop/rdof/index.html?coopCode=PEMDUNK`.
1. If that parameter exists we fetch the [`clients.json`](https://github.com/Conexon/Conexon.github.io/blob/master/coop/data/clients/clients.json) file and look for that client `coopCode`.
1. If it's found we use the data from that json object to load (and render) the tilesets.
    1. rdof_bg_<stateAbbr> (block groups)
    1. rdof_block_<stateAbbr> (blocks)
    1. rdof_meters_<stateAbbr> (meters)
1. We then fetch the client substation geojson, e.g. [pemdunk_sub.geojson](https://github.com/Conexon/Conexon.github.io/blob/master/coop/data/clients/pemdunk_sub.geojson).
    1. We use this file to render the clients substations and add a click event to them.
    1. When a substation is clicked the client substation geojson file is used to get metric data (reserve dollar amounts, FCC location counts, meter counts, etc).
    1. This data is broken down in different ways though,
        1. Some data is attributed directly to the substation itself (meter data).
        1. Other data is attributed to block groups that intersect with that substation (FCC locations, dollar amounts)

That data break down is where the change to block group has issues. The block group itself doesn't have the meter data.

## Possible solution

We create a new json file, `<coopCode>_bg.json`, that contains all the necessary data to show the metrics and push these to the [clients](https://github.com/Conexon/Conexon.github.io/tree/master/coop/data/clients) directory. _I'm sure there are other possible solutions, this is just one idea._

### Example format

```json
[
  {
    "geoid": "290693610002",
    "amount": 1183830,
    "amount50": 1183830,
    "fcc_locations": 143,
    "pct_coverage": 50,
    "meters": 973,
    "meters_rdof": 126,
    "meters_cable": 592,
    "meters_fiber": 0,
    "meters_telco": 696,
    "meters_no_service": 151,
    "meters_underserved": 223
  },
  // more block groups
]
```

The `pct_coverage` is "kind of new". It would allow us to display information about the selected (highlighted) block groups, e.g. total number selected and total number selected with 50% or greater coverage.

Having these properties would allow us to display the data per block group (and as a total for multiple block selections) on a block group click event.

On the click of a block group we would:
- already have a list of selected (highlighted) block groups (if any),
- loop through the `<coopCode>_bg.json` file pulling in the data for each highlighted block group,
- do any math required to render the totals,
- and display the data.
- We also would use the list of selected (highlighted) block groups to update the Mapbox filter to highlight the correct block groups as "red".

The "highlight all block groups" function would be essentially the same as above, loop and calculate, although we can do the "all" calculations on the initial load of the data (no need to do loop again).

_Note: this does not remove the `<coopCode>_sub.geojson` files. We can still use them to render substations and display meters. All of this doesn't remove that need, it just changes the substation click event to __only__ display meters._

**Comment by feomike** [comment]
@awolfe76 - going to take a day (or 2) to digest.

**Comment by awolfe76** [comment]
> seems really strait forward. was hoping the solution was like this, where it is a new Json (making sure this is NOT geoJson) file. assume that be in the ./data/clients/ folder.

Yeah, I was thinking to put the new files in the same location as the `<coopCode_sub.geojson>` files. So yes, [`coop/data/clients`](https://github.com/Conexon/Conexon.github.io/tree/master/coop/data/clients).
And also yes, the new files should be just json (not geojson). We have the `rdof_bg_` tilesets in Mapbox, so the new json `geoid` just need to match a geoid from the tileset (which it should). We don't need geojson because we don't need to render any data on the map with it.

> pct_coverage would have 3 categorical responses `[0,50,100], is that right?

If that's easiest for you I think that's fine. My thought though was that for data display purposes if we have the actual number I could figure out if the block group had "At 50% meter coverage" but just checking that number and seeing if it is `>= 50`. Having the actual number would let us change things in the future too; when new requirements come.

**Comment by feomike** [comment]
right, actual number would be easier.  and yes, confirming `>=50`

**Comment by feomike** [comment]
@awolfe76  first (crawl) cut.  this make sense?
```
[
  {
	'amount': 656668,
	'meters': 68,
	'geoid': '290179503001',
	'pct': 10,
	'locations': 654
}, {
	'amount': 249399,
	'meters': 40,
	'geoid': '290179503003',
	'pct': 16,
	'locations': 248
}
]

**Comment by awolfe76** [comment]
Yep, the format looks 👍.

**Comment by feomike** [comment]
@awolfe76 
couple quick deviations from yours;
 - `locations` is number of fcc locations that are eligible in that block group
- `meters` is the number of meters from the coop that are in eligible blocks
- `pct` is the percent of meters in eligible blocks to FCC locations

i don't think you need total meters in the block group; sound right?
am trying to remember if the fcc data (e.g. `meters_cable` represents any meter in a cable footprint or eligible meters in a cable footprint - i _think_ the latter)

**Comment by feomike** [comment]
v2
```
[{
	'locations': 654,
	'pct': 10,
	'amount': 656668,
	'meters': 106,
	'meters_no_service': 53,
	'meters_underserved': 0,
	'meters_fiber': 53,
	'meters_rdof': 68,
	'meters_cable': 0,
	'geoid': '290179503001',
	'meters_telco': 0
}]
