### ISSUE TITLE
move amount label from poly to point

### ISSUE THREAD

**Issue by feomike** [Conexon/Conexon.github.io#24]
the block group label, which is really important for the pitch, is currently the annual amount of money from the FCC.  Unfortunately, MapBox uses an algorithm to place label on polygons, often placing multiple labels per polygon.  this will be confusing to clients, who might think they get more than the single amount per polygon.

- MapBox's fix is to create a tileset for the centroid and label that.  
- will need to change the template to update this 
- might need to change one or two things in the labelling.

am going to start working on this, before we get too far down this path

cc @awolfe76

**Comment by awolfe76** [comment]
Want me to give this a shot, https://turfjs.org/docs/#centroid, before trying to create a new tileset?

**Comment by feomike** [comment]
@awolfe76 - yup, that looks cleaner.  got time?

**Comment by feomike** [comment]
will also create a back-up for this w/ set of geoJson objects

**Comment by awolfe76** [comment]
#25, #28, and #29 close this.
