### ISSUE TITLE
add satellite view to `blockGroups` map

### ISSUE THREAD

**Issue by feomike** [Conexon/Conexon.github.io#331]
@awolfe76 - have a client request to have a switch on the RDOF `blockGroups` map to swap base maps from the black and white to the satellite view.

can you assess, and let me know what you think of this feature request?

**Comment by awolfe76** [comment]
I responded to the email thread looking for a little more detail and asking if we could maybe publish a separate map for them if all they want is to see a satellite view of their coop.

_I'm a little hesitant to add that functionality at this point given there is a good bit of data maintenance involved and all of our clients are using it. It's not impossible at all, just would rather keep with the "single purpose" use of the RDOF map._

**Comment by feomike** [comment]
lets close ... 

@awolfe76 (?)

**Comment by awolfe76** [comment]
Yeah, when we dug a little bit they were looking for something different. We ended up sending them shapefiles so they could use them in another tool that they had.
